import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SignIn } from "@/components/sign-in";
import { SignOut } from "@/components/sign-out";
import DisplaySession from "@/components/display-session";
import { auth } from "@/auth";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  console.log(session)
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex gap-32 justify-center text-blue-500">
          <div className="flex justify-center items-center gap-4">
            <Link href={'/'}>Home</Link>
            <Link href='/create'>Create</Link>
            {session?.roles.find(item => item === 'admin') && <Link href={'/admin'}>Admin</Link>}
          </div>
          <div className="flex justify-center items-center gap-4">
            <DisplaySession/>
            {!session && <SignIn/>}
            {session && <SignOut/>}
          </div>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
