services:
  mongo:
    image: mongo

  postgres:
    image: bitnami/postgresql:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: change_me
    restart: always

  keycloak:
    image: bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: db_user
      DB_PASSWORD: change_me
      KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.migration.action=import 
                            -Dkeycloak.migration.provider=singleFile
                            -Dkeycloak.migration.file=/opt/bitnami/keycloak/data/import/realm.json 
                            -Dkeycloak.migration.strategy=OVERWRITE_EXISTING 
                            -Dkeycloak.migration.usersExportStrategy=SAME_FILE
                            -Dkeycloak.profile.feature.upload_scripts=enabled
                            -Dkeycloak.migration.realmName=blog"
    depends_on:
      - postgres
    volumes:
      - ./keycloak/realm.json:/opt/bitnami/keycloak/data/import/realm.json
    restart: always

  # backend:
  #   build: ./backend
  #   ports:
  #     - 8000:8000
  
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 3000:3000

volumes:
  postgres_data: