apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: bitnami/keycloak:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgres
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: db_user
            - name: DB_PASSWORD
              value: change_me
            - name: KEYCLOAK_EXTRA_ARGS
              value: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/bitnami/keycloak/data/import/realm.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING -Dkeycloak.migration.usersExportStrategy=SAME_FILE -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.realmName=blog"
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          volumeMounts:
            - name: keycloak-realm
              mountPath: /opt/bitnami/keycloak/data/import
      volumes:
        - name: keycloak-realm
          configMap:
            name: keycloak-realm-config
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak
# spec:
#   selector:
#     app: keycloak
#   ports:
#     - protocol: TCP
#       port: 8080
#       targetPort: 8080
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: my-blog
spec:
  selector:
    app: keycloak
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32002